### PR TITLE
Tweak Japanese translation

### PR DESCRIPTION
**Pull request by koh-gh**
Revived "material.tconstruct.wood.format" (see https://github.com/SlimeKnights/TinkersConstruct/issues/5085)

### CODE REVIEW

**Comment by KnightMiner** [comment]
Sorry for the lack of response on this translation. Currently it has some conflicts due to a rework to help addons add contents to the book. If you fix those conflicts I can merge this, otherwise I will check again when the inevitable bug fix update comes for 1.18

**Comment by koh-gh** [comment]
It's been a while since I created this, so I'll check the amount of differences and update it in a few days if it's small

**Comment by KnightMiner** [comment]
Should be as simple as just merging and then pushing, at a quick test it was a clean merge when I tried it through git, just cannot do so via github for some reason.

That is, unless you want to translate some of the new files.

**Comment by koh-gh** [comment]
If you think you might not be able to merge this PR, I'll close it and send another PR
And I want the translations to be up to date

**Comment by koh-gh** [comment]
The problem seems to be resolved?

**Comment by KnightMiner** [comment]
Conflicts look to be resolved now, will look into merging some time tomorrow.

**Comment by koh-gh** [comment]
I updated ja_jp.json and renamed the files of the already included book translations
I'll do the rest next time

**Pull request merged**
