### PR TITLE
Create pl_pl.json

### PR DESCRIPTION
**Pull request by joker876**
I just finished fully translating the mod to Polish. Some translations are not possible to be made accurately, but I tried my best and came up with my own jokes here and there.

As for the fix, it's just a single typo in en_us.json

### CODE REVIEW

**Comment by KnightMiner** [comment]
Keep the typo fix separate from this PR, just makes it harder to process when a PR does multiple things. As I said on the other PR, if that is the only one you found it is much easier for me to just fix myself.

To be clear so it does not sound like I am being inconsistent, "fixing many typos" is a fine topic for a single PR (if you fix enough typos). "Fixing typos and translating" means now I have two unrelated things that depend on each other to merge.

**Comment by joker876** [comment]
Sorry, I honestly didn't know how to remove that commit from here so I decided to stick with it. Will not do that again.

I can do _something_ about it, though. Just tell me what (and how, if needed), and it will be done.

**Comment by KnightMiner** [comment]
Reverse the change and commit the reverse. In other words, bring back the typo and commit bringing it back

**Comment by joker876** [comment]
Reversed the commit

**Comment by joker876** [comment]
Are you going to merge the PR? It's been more than 3 months since I fixed the issue you asked for.

**Comment by KnightMiner** [comment]
The mod is in an alpha state and is constantly getting language changes, translations are super low priority. I honestly would have suggested holding off until a beta release, but translations already exist.

I will likely go though and review a bunch of the translations in the near future as they have started to pile up, and a partially complete translation is a better starting point than no translation if someone wanted to make an updated translation.

**Pull request merged**
