### PR TITLE
New Textures

### PR DESCRIPTION
**Pull request by Futureazoo**
Textures for Slime things, extenders, and a couple ingots/nuggets.

### CODE REVIEW

**Comment by bonii-xx** [comment]
Keep the old pigiron nuggets, and what did you change about the ardite ingot?
Also please squash the commits.

**Comment by Futureazoo** [comment]
Slight outline changes -  I made the outline of the ardite ingot more consistent in color.

**Comment by C1ffisme** [comment]
The slime stuff looks good, keep up the good work!

**Comment by bonii-xx** [comment]
Finally had time to check the details on the ardite ingot. Keep the old one. Same goes for the pigiron nuggets. Remove those two and then squash the commits, then we can pull it in.

**Comment by Futureazoo** [comment]
Okay, I clearly have no idea what I'm doing here, it appears I'm just breaking everything. How do you suggest I proceed?

**Comment by Futureazoo** [comment]
I'm closing this pull request and trying again, sorry for the mess.

**Pull request closed without merging**
