### PR TITLE
Fix tiny typo in EFLN description (save -> safe)

### PR DESCRIPTION
**Pull request by SharkWipf**
Unless you meant they should be saved for mining of course.  
(Felt like overkill to submit an issue for this while it's a 1 letter change)

### CODE REVIEW

**Comment by SharkWipf** [comment]
Didn't realize a PR would go through CI even before approval, for future reference, would you prefer stuff like this as issue or as PR?

**Comment by C1ffisme** [comment]
@SharkWipf On the other hand, you could also interpret this line as "Save this for mining, don't bother using it on mobs." but I don't think that's what the sentence was meant to portray.

**Comment by SharkWipf** [comment]
@C1ffisme especially given how much fun it is to use on mobs, they made sure it is still useable for [Tera-jumping](http://wiki.nosebud.de/wiki/Terajump) too

**Comment by LovelyFlare** [comment]
It's certainly not safe for mining if you're being damaged by it when you're close to it...

**Comment by SharkWipf** [comment]
@LovelyFlare I think they mean "safe" as in "it doesn't destroy drops", as opposed to regular TNT which does destroy a percentage of the drops.

**Comment by C1ffisme** [comment]
@SharkWipf Ah, okay. I haven't tested the EFLN's too much yet.

**Comment by LovelyFlare** [comment]
@SharkWipf That's an extremely bad way of wording it then...

**Comment by bonii-xx** [comment]
PRs are fine, the hook is just there to check if it compiles. Teraflints obviously are the safest thing for mining ever.

**Pull request merged**
