### PR TITLE
Added Screenshot and Textures

### PR DESCRIPTION
**Pull request by ghost**
1.15 New Textures (3 screenshots)

### CODE REVIEW

**Comment by KnightMiner** [comment]
As I stated multiple times on Discord, screenshots are for the pull request description, so we can see what the textures you are adding look like. Actual textures need to be in the pull request. Put the textures where they belong in the mod, you had to have them there to make the screenshots. We don't care about 1.15 screenshots for the final product, they do not benefit the mod at all and are just so we can see what you changed.

**Comment by ghost** [comment]
Submited all smeltery textures.
Smeltery part is done

**Comment by ghost** [comment]
Tinkers Construct is MIT licensed and I agree to MIT licenses for those textures.

**Comment by futurenp** [comment]
I approve of my textures being licensed under the MIT license

**Comment by ronuseless** [comment]
I approve of my textures being licensed under the MIT license

**Pull request merged**
