### PR TITLE
Simplified Chinese Translation Support (1.19.2)

### PR DESCRIPTION
**Pull request by Cactusstudent**
Notice: This is the first edition of the translation, so maybe there will be some typos or mistakes, i'll fix them in the next couple of weeks. The translation copied from the 1.18 and updated based on the en_us in 1.19. It is still in progress.

给中国玩家的话（Something to Chinese players）：
这是一个不太完整的 1.19 翻译，由于我目前正在进行三个版本的汉化更新和维护，时间未必充裕。1.19 的手册汉化工作将在1.18 手册校对工作完成后再进行。同时，该翻译工作仍在进行，当前版本不代表最终品质。

TODO List
- [x] 匠魂宝典：材料与你丨Material And You
- [x] 入门熔炼术丨Puny Smelting
- [x] 大师熔炼术丨Mighty Smelting
- [x] 工匠装置宝典丨Tinkers Gadgetry
- [x] 奇异熔铸术丨Fantastic Foundry
- [x] 工匠大百科丨Encyclopedia
- [x] zh_cn.json丨zh_cn.json
- [x] 审核与修正丨Review and correct ( LTS )

Chinese Translation Update Log:
**April 28 2024**: Update zh_cn based on Plated Armor Tweak, and update the translation of reinforcements.
**May 2 2024**: Translation the new content and invite ChuijkYahus to review that.
**May 4 2024**: Update zh_cn based on English, and then translate some of content.
**May 5 2024**: Translate zh_cn, then fix typo.
**May 6 2024**: Reduce the speed of translation follow-up because the English content changes so fast than I expected. Maybe two weeks for one update?
**May 7 2024** : Update zh_cn based on Alpha version 3.8.2.32
**May 19 2024**: Translate zh_cn update in May 7, nothing backported to 1.18
**May 22 2024**: Update and translate zh_cn.json, and part of the Guide book, so it's still WIP, need another translation commit
**May 25 2024**: Update and translate zh_cn.json based on 3.8.3, and then fix some typo, plan to release a Chinese Language patch (Resoucepack) for Chinese community. 
**Aug 14 2024**: Change the translation of enderbark roots
**Sept 16 2024**: Fix typo and then update the translation

### CODE REVIEW

**Comment by KnightMiner** [comment]
I'd probably hesitate to put too much work into translating on 1.19 given I still need to pull in current 1.18 pull requests and content is not yet stablizing, so there is going to be some redundant work as I sort things out.

**Comment by Cactusstudent** [comment]
> I'd probably hesitate to put too much work into translating on 1.19 given I still need to pull in current 1.18 pull requests and content is not yet stablizing, so there is going to be some redundant work as I sort things out.

Thanks, I've backported the translation changes to 1.18. In fact, 1.18 and 1.19 translation project have been marked as the LTS by me. So, dont worry, we will continue to support 1.18.

**Comment by KnightMiner** [comment]
Planning to work on 1.18 again to get some bug fixes and translations updates. Would you rather I copy #5191 to 1.19 when doing so or leave 1.19 as is?

**Comment by Cactusstudent** [comment]
Thanks for asking. Just keep this PR, #5191 is still in active. And tbh, the differences between two versions have gradually increase, copy the old translation may leave many problems. So if you change your focus to 1.18, maybe I'll consider marking this PR as draft until you turn your focus back on 1.19 again.
In short, except 1.16, these two versions still in LTS position.

**Comment by KnightMiner** [comment]
To be clear, I'm merging 1.18 pull requests shortly as I want to do a big fix release there. The question is just whether I copy the results of that language PR merge to the 1.19 branch or not.

**Comment by Cactusstudent** [comment]
> To be clear, I'm merging 1.18 pull requests shortly as I want to do a big fix release there. The question is just whether I copy the results of that language PR merge to the 1.19 branch or not.

I think not copied is better for me, and sorry for my misunderstanding.

**Comment by KnightMiner** [comment]
This last commit I pushed (stone plating parts) should be the last change affecting language before a new build. Will probably try to get one up tomorrow evening, so get whatever you want done before then and I'll merge this PR.

**Comment by Cactusstudent** [comment]
OK, thanks. I have pushed maybe the last commit, so this PR has finished all work.

**Pull request merged**
