### PR TITLE
New bricks

### PR DESCRIPTION
**Pull request by TherminatorX**
Alumite, ardite, cobalt, and manyullyn bricks and fancy bricks. Plus old
smooth textures for decorative reasons, as per #1594.

### CODE REVIEW

**Comment by bonii-xx** [comment]
No chiselling integration? :(

**Comment by laz2727** [comment]
You asked for the textures. Here they are.

2015-06-26 12:57 GMT+06:00 boni <notifications@github.com>:

**Comment by TherminatorX** [comment]
I agree with @laz2727, you only asked for textures. I'm not in a position where I can quick-learn the code used and reapply it.
If you didn't want to add those blocks, please just outright state so in the future.

**Comment by bonii-xx** [comment]
It'll just take longer that way :P

**Pull request merged**
