### PR TITLE
Ore dict everything

### PR DESCRIPTION
**Pull request by Adaptivity**
Hope I didn't broke something.

### CODE REVIEW

**Comment by bonii-xx** [comment]
Oh, nice!
Now go and test it so you know you didn't break something ;P

**Comment by Adaptivity** [comment]
Can you build this for me? I have some problems with gradle when I'm building Tcon I'm getting "A problem occurred evaluating root project "TConstruct"". Then I can test it :smile:

**Comment by bonii-xx** [comment]
Test the next build ;P

**Comment by Adaptivity** [comment]
Tested. During testing I was unable to find any bugs. So, I guess it's all good.

**Comment by bonii-xx** [comment]
yay

**Pull request merged**
