### PR TITLE
Hide technical stuff from NEI

### PR DESCRIPTION
**Pull request by Adaptivity**
These:
javaw 2015-10-03 13-42-14-11
Tested and it's working.

### CODE REVIEW

**Comment by Adaptivity** [comment]
ping @bonii-xx

**Comment by bonii-xx** [comment]
The better course of action would be to not add those items/blocks to the creative menu, instead of hiding them in NEI. The boneana already does this.

**Comment by Adaptivity** [comment]
These items aren't available in creative tabs. However, they are available in NEI.

**Comment by Adaptivity** [comment]
So, what do you think?

**Comment by bonii-xx** [comment]
See what I said above.

**Pull request closed without merging**
