### PR TITLE
ru_RU death messages addition

### PR DESCRIPTION
**Pull request by Mexahoid**
Bleeding?

### CODE REVIEW

**Comment by bonii-xx** [comment]
Bleeding is from the steel trait. Looks like you forgot a few entries: https://github.com/SlimeKnights/TinkersConstruct/commit/3abf6b36fc7b99a245dde318f46d5c4e7ef6ed25

**Comment by Mexahoid** [comment]
Oh god, what have I done. Could you close that PR please? I'll make it as one commit later.

**Comment by bonii-xx** [comment]
No need, looks fine to me?

**Comment by Mexahoid** [comment]
Well, I wanted to pull only one commit, but if you can squash it,  it'll be fine.

**Comment by bonii-xx** [comment]
We can squash and merge nowadays in github, yes, no need to squash them manually anymore :)

**Pull request merged**
