### PR TITLE
Update ko_KR.lang

### PR DESCRIPTION
**Pull request by alvin137**
Sync with en_US.lang

### CODE REVIEW

**Comment by bonii-xx** [comment]
It seems you aren't finished with it yet?

**Comment by alvin137** [comment]
I've not finished yet. but almost finished. 
Just need to translate some effects.

**Comment by bonii-xx** [comment]
Just post here when the remainder is translated

**Comment by Adaptivity** [comment]
@bonii-xx close it. Another PR merged.

**Pull request closed without merging**
