### PR TITLE
New villager textures

### PR DESCRIPTION
**Pull request by Drullkus**
@alexbegt requested these. Tada! :3

### CODE REVIEW

**Comment by bonii-xx** [comment]
Yeah, I totally want some improved/diverse village stuff. Also looking for people who want to design a few house/smeltery variations ;o

**Comment by Drullkus** [comment]
Yes Boni I can do that, I'm at work but can do that when I get home. :)

**Comment by Drullkus** [comment]
Added gadget guy, fixed issues with zombie variants

**Comment by bonii-xx** [comment]
We're not in a hurry or anything ;)

**Pull request merged**
