### PR TITLE
1.16

### PR DESCRIPTION
**Pull request by MrSvyatik**
https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL  ukrainan translate TConstruct-1.16.5-3.3.4.335

### CODE REVIEW

**Comment by MrSvyatik** [comment]
> https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL ukrainan translate TConstruct-1.16.5-3.3.4.335

**Comment by MrSvyatik** [comment]
> https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL ukrainan translate TConstruct-1.16.5-3.3.4.335

**Comment by MrSvyatik** [comment]
https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL ukrainan translate TConstruct-1.16.5-3.3.4.335

**Comment by alexbegt** [comment]
The link you provided to google drive for the translation is not a public link. so, we are unable to verify that this is a translation. Please upload the translation to and [gist.github.com](https://gist.github.com/) provide the link to it here. If you would like it added.

**Comment by KnightMiner** [comment]
Going to actually close this. Once you do what Alexbegt said (create the translation on gist.github.com), open a new issue as an enhancement. And link the gist there.

We told you to make a pull request originally, but this is not how you make a pull request, if you are just going to link the file its easier to do an issue than to walk you through using regular github.

**Comment by MrSvyatik** [comment]
[RobloMinerYT](https://github.com/RobloMinerYT)
RobloMinerYT commented [11 hours ago](https://github.com/SlimeKnights/TinkersConstruct/pull/4859#issue-1236413938) • 
https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL ukrainan translate TConstruct-1.16.5-3.3.4.335

**Pull request closed without merging**
