### PR TITLE
RU Translation

### PR DESCRIPTION
**Pull request by Cubichesky**
This Russian translation was made on the version of TConstruct 3.0.3.152

### CODE REVIEW

**Comment by KnightMiner** [comment]
There is currently a second translation pull request open for russian at #4344. Please talk to that author and resolve any potential differences.

**Comment by Cubichesky** [comment]
> В настоящее время открыт второй запрос на перевод на русский язык по адресу #4344. Пожалуйста, поговорите с этим автором и разрешите любые потенциальные разногласия.
He hasn't appeared on github for a long time, and I can't get an answer from him

**Review by intimniy — APPROVED** [review]

**Review by intimniy — APPROVED** [review]

**Comment by Cubichesky** [comment]
I will update the translation later.

**Review by BurAndBY — APPROVED** [review]
Very good, no errors and clean translation

**Comment by Cubichesky** [comment]
> 
> 
> Very good, no errors and clean translation

Russian? If yes, can i ask you? Help me with translate this mod. Check new translation.

**Comment by BurAndBY** [comment]
> > Very good, no errors and clean translation
> 
> Russian? If yes, can i ask you? Help me with translate this mod. Check new translation.

Sure! You can contact me here - BurAndBY#3025. I'll try to help you as soon as I can

Конечно! Напиши сюда - BurAndBY#3025. Я помогу когда смогу.

**Pull request closed without merging**
