### PR TITLE
fix typo ("sandwhich" -> "sandwich")

### PR DESCRIPTION
**Pull request by joker876**

### CODE REVIEW

**Comment by KnightMiner** [comment]
Its more effort to review and test a PR like this then it is to make the change myself. I doubt this is the only typo, so if you want to scan all translations and fix errors I will look into that PR. Otherwise I will just fix this typo directly

**Comment by joker876** [comment]
I am in the process of translating the mod, and am 75% done. So far it's the only typo I found

**Comment by joker876** [comment]
It actually IS the only typo I found. Do what you will with this PR

**Comment by joker876** [comment]
Actually, I will include this fix within another PR, and close this one

**Pull request closed without merging**
