### PR TITLE
Stop irrelevant ProjectileWeapon damage tooltip being displayed when it has no ammo

### PR DESCRIPTION
**Pull request by squeek502**

### CODE REVIEW

**Comment by bonii-xx** [comment]
But what if I want to have a melee-bow? :(

**Comment by laz2727** [comment]
Don't laugh. There's nothing to do with free mod slots after maxing out
speed but filling them with melee damage.

2015-01-01 23:17 GMT+06:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
I was quite serious. The main philosophy behind tinkers is to let people do whatever they want with their stuff. I love me my battle mattock.

**Comment by squeek502** [comment]
Can you currently swing a bow?

**Comment by laz2727** [comment]
Yep.

**Comment by bonii-xx** [comment]
I'd leave the damage in for that reason. We could change it to specifically say "melee damage" though.

**Comment by squeek502** [comment]
Fair enough, didn't even think to try swinging a bow. :smile:

**Comment by bonii-xx** [comment]
I recommend filling remaining modifiers with Pistons, so you can knock enemies back to shoot them. ;)

**Pull request closed without merging**
