### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by Adaptivity**
Initial Russian localization for Tinkers 1.8.9 :smile: 
@bonii-xx few notes about en_US.lang:
1) https://github.com/SlimeKnights/TinkersConstruct/blob/rework/resources/assets/tconstruct/lang/en_US.lang#L60 maybe add colors to names? To be inline with grass and dirt.
2) https://github.com/SlimeKnights/TinkersConstruct/blob/rework/resources/assets/tconstruct/lang/en_US.lang#L67 shouldn't these be "Slimy"?

### CODE REVIEW

**Comment by Adaptivity** [comment]
@bonii-xx don't forget to merge this as I want to get this in the next release version.

**Comment by bonii-xx** [comment]
I"ll consider the localizations once the english one is done.

**Comment by Adaptivity** [comment]
Ok, I'll re-PR later.

**Comment by bonii-xx** [comment]
Calling @Adaptivity
With an alpha out I think it's save to start the first translation, if you're still doing that :)

**Comment by Adaptivity** [comment]
Not sure if I can. I mostly retired from translating, if someone do this then I can take a look (or when/if I comeback I can do this myself)

**Comment by bonii-xx** [comment]
Sure, no problem. Just figured I'd tell you since I said to wait before.

**Pull request closed without merging**
