### PR TITLE
Update zh_CN language file

### PR DESCRIPTION
**Pull request by TartaricAcid**
#1. Update some language code
#2. fix some error

### CODE REVIEW

**Comment by bonii-xx** [comment]
Please squash the commits

**Comment by bonii-xx** [comment]
Ping

**Comment by 3TUSK** [comment]
There is no squash merge option?

**Comment by bonii-xx** [comment]
We don't have GithubEnterprise.

**Comment by GirafiStudios** [comment]
I'm pretty sure that all can squash and merge now, can't they?
If I remember correctly, there is a arrow next to the merge button, where you can choose to squash :)

**Comment by 3TUSK** [comment]
It should be here [since April 1st, 2016](https://github.com/blog/2141-squash-your-commits).

**Comment by bonii-xx** [comment]
Seems we have it now. Last time I checked the settings after the announcemente we didn't have the option to enable it. It's there now. Hooray, that makes thinsg so much simpler :tada:

**Comment by RelaperCrystal** [comment]
> The translator @TartaricAcid **mistakenly** translated the modifier field of the shulking.json file. This field **cannot be translated**. This error led to the Tinker's manual being up for half a year, Chinese players would **crash when they opened it**.
original:
> 翻译者 @TartaricAcid **错误的**翻译了 shulking.json 文件的modifier 字段，此字段**不能够**翻译。该错误导致匠魂手册在长达半年的时间，中文玩家**一打开就会游戏崩溃**
(Machine Translated by google translate and changed for style, may have error.)

**Comment by KnightMiner** [comment]
This pull request was made 2 years ago. If it is still an issue in the current code, open a new issue for it

**Comment by 3TUSK** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/book/zh_cn/tools/shuriken.json#L2
False positive, the issue you described has been addressed a long time ago.
@RelaperCrystal 你所描述的问题现在根本不存在。

**Comment by 3TUSK** [comment]
To be exact, #2580 addressed that issue.

**Comment by 3TUSK** [comment]
To be exact, #2508 address that issue.

> Was mistakenly typed 2580. Just for record.

**Comment by TartaricAcid** [comment]
The bug has been fixed in 21 Oct 2016.
> https://github.com/SlimeKnights/TinkersConstruct/pull/2508

**Pull request merged**
