### PR TITLE
Add palettes for all materials and generate toolpart textures

### PR DESCRIPTION
**Pull request by RCXcrafter**
- Every material has a palette added in the data generator
- The ui render materials use existing generated textures now
- Fallback colors have been updated to match the new palettes
- Unique textures have been added for flint, pig iron and slimewood large plates

Images:
image
image
image

### CODE REVIEW

**Comment by BeansBeefBroccoli** [comment]
This pull probably has the same problem @KnightMiner mentioned in #4652.

**Comment by KnightMiner** [comment]
No, RCXcrafter is our mods artist, and I specifically requested for him to make this pull request on our discord. Its a thing I could have coded myself if he sent me palettes, but was easier for him to just add them in code.

For the record, the files added by this PR are generated via data generators, which is pretty easy to verify as Forge ensures nothing wrong is saved next time datagenerators run. So yeah, its a lot of files, but in this case its a little easier to verify

**Comment by BeansBeefBroccoli** [comment]
> No, RCXcrafter is our mods artist, and I specifically requested for him to make this pull request on our discord. Its a thing I could have coded myself if he sent me palettes, but was easier for him to just add them in code.
> 
> For the record, the files added by this PR are generated via data generators, which is pretty easy to verify as Forge ensures nothing wrong is saved next time datagenerators run. So yeah, its a lot of files, but in this case its a little easier to verify

Oh lol ok sorry 😆

**Comment by RCXcrafter** [comment]
Maybe I should put "as discussed on discord" in future PRs so it doesn't look like they just get pulled without any discussion.

**Pull request merged**
