### PR TITLE
Update ArmorControls.java

### PR DESCRIPTION
**Pull request by TheTemportalist**
Updates for NeK 2.0.1, and in the process fixing https://github.com/mod-warriors/NotEnoughKeys/issues/34
Requires testing (could not get TiCon to setup workspace on local machine, changes were made via github.com).

### CODE REVIEW

**Comment by bonii-xx** [comment]
I'm not pulling any untested changes. What's furthermore is that it's caused by an API change on your side. That shouldn't break anything.

**Comment by TheTemportalist** [comment]
Api changes are meant to be changed on the side of those implementing it. APIs are never completely finished. That's why we use SemVer versioning.

**Comment by Adaptivity** [comment]
@bonii-xx are you going to pull this?

**Comment by bonii-xx** [comment]
I thought I already head. Probably wanted to wait in case more fixes for it were coming.

**Comment by Adaptivity** [comment]
Thanks!

**Pull request merged**
