### PR TITLE
Update pt_BR.lang

### PR DESCRIPTION
**Pull request by al-myr**

### CODE REVIEW

**Comment by LorenzoDCC** [comment]
You changed the unlocalised names (item.InfiTool.excavator) and that breaks the translation :l 
Also, "Tinkereiro" is "funileiro" ('to tinker' is 'funilar' and etc) (could as well be 'consertador', yet the first fits more) and you took out the 'equals' in the line nº924, breaking the translation again :l 
(The fact that you finished translating a lot of mods before me is making me paranoid about translations, sorry about that :joy: )

**Comment by al-myr** [comment]
> You changed the unlocalised names (item.InfiTool.excavator) and that breaks the translation :l 
> Also, "Tinkereiro" is "funileiro" ('to tinker' is 'funilar' and etc) (could as well be 'consertador', 
> yet the first fits more) and you took out the 'equals' in the line nº924, breaking the translation again :l 
> (The fact that you finished translating a lot of mods before me is making me paranoid about translations, sorry about that :joy: )

I translated or completed 40 or so mods... And I have to keep them always updated. :D
Some were easy to translate... others hard... others tiresome... and others very fun :)

Some words, however, are common to modders but not very common to the casual players of the game.

example: "crescent hammer" literally translated to portuguese is "Martelo Crescente" (???)

After listening to a brazilian youtuber getting confused because of the translated name of the item, I did some research and found out about the actual "crescent hammer" tool: http://www.amazon.com/Crescent-DB16-16-Inch-Adjustable-Puller/dp/B008NM6VFU
"Crescent" is a brand from a company and the "Hammer" is not just a hammer... it's some kind of multi-tool I've never seen before...

About TC's corrections:

** Sorry 1! :~(
 | #tool.shovel.kingslime=Regret
 
My translation spreadsheet sometimes fails when there's more than one "=" symbol in the same line, or one "=" symbol in a comment line (which happened this time around).

** Sorry 2! :~(
- 11 days ago
(en_US.lang)
 | item.InfiTool.Excavator.name=Excavator
 | toolpart.ExcavatorHead=%%material Excavator Head


- 13 Jan Update
(pt_BR.lang)
 | item.InfiTool.Escavador.name=Escavador
 | toolpart.EscavadorHead=Cabeça do Escavador de %%material


- current Update
(pt_BR.lang)
 | item.InfiTool.Excavator.name=Escavador
 | toolpart.ExcavatorHead=Cabeça do Escavador de %%material
 
I didn't notice I already had accidentally replaced some instances of "Excavator" for "Escavador"
 
It's a little tough to recheck 1000 lines of text alone...

 ** Tinkereiro
I was looking for a word to better translate "Tinker", but didn't find one that fits well with the mod.
"Funileiro" here in Brazil means "someone who repairs cairs". While that's something Tinkers do, it doesn't cover all other proficiencies the word covers. And the mod is not about car repairing.
"Consertador" sounds very strange. It's not a very common word in Brazil, maybe it's more used in Portugal....
The english word Tinker doesn't have an exact meaning in portuguese, it means a lot of different activities. You can confirm this by looking at how the portuguese translation of The Sims 2 translates the word: http://pt-br.sims.wikia.com/wiki/Fa%C3%A7a-Voc%C3%AA-Mesmo "Do-it-yourself".
 
Also, if the word Tinker is included in the name of the mod (Tinkers Construct, a proper name, therefore not translatable), adding the portuguese suffix "eiro", turning it into "Tinkereiro", should help most people into understanding it better while still maintaining a connection with the mod's name.

Thanks for the feedback! :D

[]s

**Comment by bonii-xx** [comment]
This vs. https://github.com/SlimeKnights/TinkersConstruct/pull/1413
From the looks of it the other one looks better. Any other brazil people around?

**Comment by bonii-xx** [comment]
Closing this in favor of #1413

**Pull request closed without merging**
