### PR TITLE
Update Japanese translation(1.18)

### PR DESCRIPTION
**Pull request by koh-gh**
Almost all same as https://github.com/SlimeKnights/TinkersConstruct/pull/4707
And added 1.18 items.

### CODE REVIEW

**Comment by koh-gh** [comment]
I couldn't create a clean branch for 1.18 because I have a PR out for 1.16. Please forgive me if you see many extra commits.

**Comment by koh-gh** [comment]
This is for Japanese contributors.
いつも指摘ありがとうございます。このPRは1.16向けと基本的には同じですが、以下の違いがあります。
- アメジストに関連するアイテム(クリア遮光ガラス、各種スライムクリスタルの芽)の追加
- 各種プラットフォームと金格子の追加
- アメジストの改造「神速」の追加と、これによる速度増加効果の変更(赤石は採掘速度、アメジストは攻撃速度)
- ピックアッズの追加
- 道を作る能力がマトックからピックアッズに変更
- 耕す能力が鎌からマトックに変更
- ダイヤモンドを防具に適用した際の上昇率の変更(Encyclopedia)
- 液体コンテナ容量を増やす改造1回で増える容量が全て1バケツ分に統一(Encyclopedia)
- ジオードの説明の追加(Tinker's Gadgetry)
これらに関する誤りや指摘については、こちらにお願いします。その他については、https://github.com/SlimeKnights/TinkersConstruct/pull/4707 にお願いします。

**Comment by KnightMiner** [comment]
Sounds like you need a bit of practice with git, likely something you cannot do on the web interface. You need to create a new branch based on the 1.18 branch

Try rebasing your branch compared to our 1.18 branch. It should be possible in the GitHub desktop client, but you might have to Google how to do it command line

**Comment by koh-gh** [comment]
I think I can only create a branch from my existing branch, but is it possible to copy the entire branch from forking repo? If so, I try a little search. Maybe I'll ask you a question on Discord.

Can I do it directly on this branch? If not, I'm going to close this PR once and send again.

**Comment by KnightMiner** [comment]
If you take my second suggestion (rebasing), it should be doable from this branch. Requires a git client such as Git or Github desktop (second is easier for beginners).

Opening a new PR might be easier, or waiting for the 1.16 PR to be merged.

**Comment by koh-gh** [comment]
As a result of talking to @KnightMiner on Discord, I will close this PR.
I will send 1.18 PR again at a later date.

**Pull request closed without merging**
