### PR TITLE
Remove TF material strings

### PR DESCRIPTION
**Pull request by Adaptivity**
Plus some other localization fixes. Also, added Italian localization for manuals by @TheVikingWarrior. Closes #1573
Reworked version of #1475

### CODE REVIEW

**Comment by bonii-xx** [comment]
Nice. Do all the books work now? The materials added by TF have their own localization in TF right?

**Comment by Adaptivity** [comment]
1) The books(Italian books) working for me. I dunno why they not working for @TheVikingWarrior might be an issue on his side. 2) [Yes, they have](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/resources/assets/thermalfoundation/lang/en_US.lang#L296)

**Comment by bonii-xx** [comment]
Well, he said only one or two didn't work but the remaining ones did.

**Comment by Adaptivity** [comment]
All of them works for me... anyway, merge this, there is nothing what I can fix.

**Comment by bonii-xx** [comment]
Okay, just wanted to make sure. Thanks Adaptivity :)

**Pull request merged**
