### PR TITLE
Add book

### PR DESCRIPTION
**Pull request by Mexahoid**
I think I did smth wrong

### CODE REVIEW

**Comment by LovelyFlare** [comment]
Looks okay to me :P

**Comment by Mexahoid** [comment]
@LovelyFlare Well, instead of squashing commits, I deleted old branch and made new. (I don't have bash nor any bash-like git tools).

**Comment by LovelyFlare** [comment]
@Mexahoid I was planning to do the same exact thing when I finished my translation... though that is long delayed >.>

**Comment by Mexahoid** [comment]
@LovelyFlare Oh, ok. So good luck with translating!

**Comment by bonii-xx** [comment]
Heh, that's the other approach ;)

**Pull request merged**
