### PR TITLE
Update pt_BR.lang

### PR DESCRIPTION
**Pull request by MrKunji**
Now with proper grammar check, words that ACTUALLY exists and elimination of typos.

### CODE REVIEW

**Comment by LorenzoDCC** [comment]
I don't really think that 'moldes' is a good translation - "estênceis" do exist, after all, and I think they fit perfectly.

**Comment by LorenzoDCC** [comment]
And this
http://pt.wikipedia.org/wiki/Esc%C3%B3ria_%28subst%C3%A2ncia%29
patric pls

**Comment by MrKunji** [comment]
Take note that there are some words I don't even had heard in my life, it's natural that I didn't have used them.

**Comment by MrKunji** [comment]
Whatever, if it isn't merged until tomorrow, I'm going to make those changes. ~But they really sound strange, seriously :|

**Comment by LorenzoDCC** [comment]
Also, while you're at it, change "lingote" to "barra", to fit in the dirty official translation of Minecraft :person_frowning: 
"Crowdin, I am disappoint"

**Comment by MrKunji** [comment]
Wait, what? Did I skip something? I changed that word in too many lines, but got no time to review today.

**Comment by LorenzoDCC** [comment]
oh, nvm, lazy lorenzo is lazy

**Comment by MrKunji** [comment]
Squashing things.

**Pull request closed without merging**
