### PR TITLE
Right Click Placement Fix

### PR DESCRIPTION
**Pull request by SamRaven2**
A re-write of the logic for placing things with tools on right click. Fixes the inaccurate logic when a player is on the edge of the block as well as allows items such as torches to be placed when the player is in the same space as them.

Allows for placing blocks underneath player more consistently (noob-towers)
Allows torches/webs/saplings/etc to be placed even if player is in same block space
Removes minor chance of being inside block when placed causing suffocation damage

### CODE REVIEW

**Comment by SamRaven2** [comment]
Okay, I think that's all the commits for now. Mostly seems to be fixed.

**Comment by bonii-xx** [comment]
Looks ok. Please squash the commits though.

**Comment by SamRaven2** [comment]
Not super familiar with git yet, is there an easy way to do that or will I need to create a new pull?

**Comment by Wulfson** [comment]
No need to create a new PR.
http://davidwalsh.name/squash-commits-git
The push -f at the end will update this PR.

**Comment by SamRaven2** [comment]
So as much as I would like to say that helped... it unfortunately did not. In the process of trying to follow it, I'm afraid that I might have messed up my working directory.

**Comment by SamRaven2** [comment]
oh, there we go
All good now

**Comment by bonii-xx** [comment]
Squashing can be weird the first time, yes. ;)
Thanks

**Pull request merged**
