### PR TITLE
ru_RU lang: Fix text color

### PR DESCRIPTION
**Pull request by Mexahoid**

### CODE REVIEW

**Comment by bonii-xx** [comment]
Hey @Mexahoid , think you can add the missing translations anytime soon?

**Comment by Mexahoid** [comment]
@bonii-xx , I think I'll do it at Saturday or Sunday. I was VERY busy that month.

**Comment by bonii-xx** [comment]
Thanks, let me know if you need more time

**Comment by Mexahoid** [comment]
Ok.

**Pull request merged**
