### PR TITLE
new textures

### PR DESCRIPTION
**Pull request by RCXcrafter**
In my opinion they look better, feel free to pick out ones you like/don't like.

### CODE REVIEW

**Comment by KnightMiner** [comment]
You cannot just change most of the textures in a PR without screenshots showing the new textures in game. Please post some of those so we can better judge this PR.

**Comment by RCXcrafter** [comment]
Good point, here are some before and after screeenshots:

Tools and toolparts in manyullyn:
image image
Pickaxes:
image image
Large plates:
image image
I also added some unique textures for certain types of materials:
image image
Some other things I changed:
image image

**Comment by bonii-xx** [comment]
Just popping in to let you know that I've not forgotten the PR. I have taken a quick look at the textures ingame, but I don't have much time to deal with it further lately. Things like these need lots of consideration, since it affects literally anybody playing the game.
So far I love the plates (slime plates <3) but am not too fond that the contrast on many materials went down. I need to take a closer look to the implementation, too. It will take some time, sorry.

**Comment by Khioni** [comment]
If there's nothing stopping this from working as such, and assuming the current sprites _will_ stay, maybe these could be made into a resourcepack and released as an add-on?

**Comment by RCXcrafter** [comment]
Good suggestion, I finally got around to actually doing it now.
https://github.com/RCXcrafter/TinkersConstruct/releases/download/resourcepack/Tconstruct_texture_edit.zip
Looking back on it I see some room for improvement but I'm not sure if I'll work on it again so here it is.

**Comment by KnightMiner** [comment]
Going to close this PR as I have no plans to add a texture update to 1.12. RCXcrafter has been helping us with 1.16 textures, and a lot of these ideas will probably end up there.

**Pull request closed without merging**
